# Generated by Django 3.1.7 on 2021-03-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MN', 'Monument'), ('TR', 'Theatre'), ('MS', 'Museum'), ('GB', 'Government building'), ('ML', 'Mall'), ('RS', 'Red Square object'), ('RB', 'Religious building'), ('RT', 'Restaurant'), ('SS', 'Skyscraper'), ('SD', 'Stadium'), ('UK', 'Unknown')], default='Unknown', max_length=100)),
                ('name_ru', models.CharField(default='', max_length=200)),
                ('name_en', models.CharField(default='', max_length=200)),
                ('wiki_ru', models.CharField(blank=True, default='', max_length=500)),
                ('wiki_en', models.CharField(blank=True, default='', max_length=500)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('address', models.CharField(max_length=150)),
                ('coordinates', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
