# Generated by Django 3.2 on 2021-05-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MN', 'Monument'), ('TR', 'Theatre'), ('MS', 'Museum'), ('GB', 'Government building'), ('ML', 'Mall'), ('RS', 'Red Square object'), ('RB', 'Religious building'), ('RT', 'Restaurant'), ('SS', 'Skyscraper'), ('SD', 'Stadium'), ('UK', 'Unknown'), ('OT', 'Other')], default='Unknown', max_length=100)),
                ('name_ru', models.CharField(default='', max_length=200)),
                ('name_en', models.CharField(default='', max_length=200)),
                ('wiki_ru', models.URLField(default=None, max_length=500, null=True)),
                ('wiki_en', models.URLField(default=None, max_length=500, null=True)),
                ('image_url', models.URLField(default=None, max_length=500, null=True)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('contributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_objects', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['category', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='LocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserObjectExploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('geo_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.geoobject')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explored_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedGeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MN', 'Monument'), ('TR', 'Theatre'), ('MS', 'Museum'), ('GB', 'Government building'), ('ML', 'Mall'), ('RS', 'Red Square object'), ('RB', 'Religious building'), ('RT', 'Restaurant'), ('SS', 'Skyscraper'), ('SD', 'Stadium'), ('UK', 'Unknown'), ('OT', 'Other')], default='Unknown', max_length=100)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('wiki_ru', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('wiki_en', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('contributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='QuadTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=20)),
                ('divided', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(default=False)),
                ('bottom_left', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BottomLeft', to='geo_objects.quadtree')),
                ('bottom_right', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BottomRight', to='geo_objects.quadtree')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.rectangle')),
                ('top_left', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='TopLeft', to='geo_objects.quadtree')),
                ('top_right', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='TopRight', to='geo_objects.quadtree')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.rectangle')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.geoobject')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.point')),
            ],
        ),
    ]
