# Generated by Django 3.1.7 on 2021-03-23 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='geoobject',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='geoobject',
            name='contributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='image_url',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='wiki_en',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='wiki_ru',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SubmittedGeoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MN', 'Monument'), ('TR', 'Theatre'), ('MS', 'Museum'), ('GB', 'Government building'), ('ML', 'Mall'), ('RS', 'Red Square object'), ('RB', 'Religious building'), ('RT', 'Restaurant'), ('SS', 'Skyscraper'), ('SD', 'Stadium'), ('UK', 'Unknown')], default='Unknown', max_length=100)),
                ('name_ru', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('wiki_ru', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('wiki_en', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('contributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='QuadTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=5)),
                ('divided', models.BooleanField(default=False)),
                ('bottom_left', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BottomLeft', to='geo_objects.quadtree')),
                ('bottom_right', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BottomRight', to='geo_objects.quadtree')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.rectangle')),
                ('top_left', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='TopLeft', to='geo_objects.quadtree')),
                ('top_right', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='TopRight', to='geo_objects.quadtree')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.rectangle')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.geoobject')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.point')),
            ],
        ),
    ]
