# Generated by Django 3.1.7 on 2021-03-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='contributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='image_url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='wiki_en',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='wiki_ru',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
