# Generated by Django 3.1.7 on 2021-03-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_objects', '0002_auto_20210323_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadtree',
            name='bottom_left',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BottomLeft', to='geo_objects.quadtree'),
        ),
        migrations.AlterField(
            model_name='quadtree',
            name='bottom_right',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BottomRight', to='geo_objects.quadtree'),
        ),
        migrations.AlterField(
            model_name='quadtree',
            name='top_left',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='TopLeft', to='geo_objects.quadtree'),
        ),
        migrations.AlterField(
            model_name='quadtree',
            name='top_right',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='TopRight', to='geo_objects.quadtree'),
        ),
    ]
