# Generated by Django 3.1.7 on 2021-03-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_objects', '0003_auto_20210323_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadtree',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
    ]
