# Generated by Django 3.1.7 on 2021-03-21 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_objects', '0004_auto_20210321_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoobject',
            name='approved',
        ),
        migrations.CreateModel(
            name='SubmittedGeoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MN', 'Monument'), ('TR', 'Theatre'), ('MS', 'Museum'), ('GB', 'Government building'), ('ML', 'Mall'), ('RS', 'Red Square object'), ('RB', 'Religious building'), ('RT', 'Restaurant'), ('SS', 'Skyscraper'), ('SD', 'Stadium'), ('UK', 'Unknown')], default='Unknown', max_length=100)),
                ('name_ru', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('wiki_ru', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('wiki_en', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('contributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
