# Generated by Django 3.1.7 on 2021-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_objects', '0005_auto_20210321_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='image_url',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='wiki_en',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='wiki_ru',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submittedgeoobject',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submittedgeoobject',
            name='wiki_en',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submittedgeoobject',
            name='wiki_ru',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
