# Generated by Django 3.1.7 on 2021-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_objects', '0005_auto_20210412_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedgeoobject',
            name='name_ru',
            field=models.CharField(max_length=200),
        ),
    ]
