# Generated by Django 3.2 on 2021-04-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_objects', '0007_auto_20210420_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjectExploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('geo_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_objects.geoobject')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explored_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
