# Generated by Django 3.2 on 2021-04-29 12:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('geo_objects', '0008_userobjectexploration'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
