# Generated by Django 3.2 on 2021-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_objects', '0009_geoobject_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadtree',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
