# Generated by Django 3.2 on 2021-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_settagsrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('RU', 'Russian'), ('EN', 'English')], default='Russian', max_length=100),
        ),
    ]
