# Generated by Django 3.2 on 2021-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('article_url', models.URLField()),
                ('image_url', models.URLField()),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
